# Generated by Django 3.0.4 on 2020-04-21 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0003_auto_20200420_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_publicated',
            field=models.BooleanField(default=False),
        ),
    ]
