# Generated by Django 3.0.4 on 2020-04-21 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0004_post_is_publicated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=3000),
        ),
    ]
