# Generated by Django 3.0.4 on 2020-04-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0005_auto_20200421_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body_text',
            field=models.TextField(default='empty', max_length=250),
        ),
    ]
