# Generated by Django 3.0.4 on 2020-04-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posters', '0006_auto_20200423_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='body_text',
            field=models.TextField(default='', max_length=250),
        ),
    ]
